import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import scanLinks from '../data/info';

export default function Home() {
  if (typeof window !== 'undefined') {
      localStorage.setItem('myCat', 'Tom');
  }

  function setCollected(link) {
    
  } 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to IKEALAND
        </h1>

      <div className='grid grid-cols-3 mt-10 border-b border-white pb-10'>

      {scanLinks.map((link, i) => (
        <div key={i} className={`border border-white rounded-full w-20 h-20 ${link.collected ? 'bg-white' : 'bg-transparent'}`} onClick={setCollected(link)}></div>
      ))}
      </div>
        
      <div className='text-xl mt-2'>
          2/6 Collected
        </div>

      </main>
    </div>
  )
}
